### ISSUE TITLE
Dimension Error with Python 3.8

### ISSUE THREAD

**Issue by Liambcollins** [pycroscopy/pycroscopy#258]
@ssomnath I got the following error when using Dimension (which broke the translators)

I was using Python 3.8.3 (and imported pyUSID 0.10.0 from master). Reverting back to 3.7 appears to have fixed the issue. Just wanted to give a heads up.

<img width="914" alt="CaptureDimension" src="https://user-images.githubusercontent.com/22297709/125350169-62c3d700-e32c-11eb-89d8-59a9703c7a7c.PNG">

**Comment by ramav87** [comment]
Thanks Liam. I don't seem to be able to find much on the python website about this, but this is the only thing that mentions __new__()

"A RuntimeError is now raised when the custom metaclass doesn’t provide the __classcell__ entry in the namespace passed to type.__new__. A DeprecationWarning was emitted in Python 3.6–3.7. (Contributed by Serhiy Storchaka in bpo-23722.)"

I can't quite decipher this though. Thoughts, @ssomnath , @ziatdinovmax , @gduscher ?

**Comment by rajgiriUW** [comment]
Hi Liam,
This is odd to me because I use 3.8.5 and haven't had this issue come up. I tried that line you posted above and it worked fine. Can you try creating a new environment and seeing if the new issue pops up? Can you confirm the pyUSID version, though I don't think that's the issue (I know you said you now have 0.10.0, so that *should* be fine)?

![image](https://user-images.githubusercontent.com/19934853/125512729-c4f6f4d3-93a3-4b4b-b329-f728692cfdfd.png)

Raj

**Comment by Liambcollins** [comment]
Hey Raj, you are right I reinstalled python 3.8.5 and all looks good. I was using 0.10.0.. I dont know what version of sidpy I was running, maybe that could have been it?

Liam
